# NumPy Basics

An open source Python  library that's used in almost every field of science and engineering. Contains multidimensional array and matrix data structures. Has strong integration with Pandas and supports mathematical lfunctions that allow you to perform linear algebra calculations

In [4]:
import numpy as np
import matplotlib.pyplot as plt

## Creating NumPy Arrays

In [6]:

# Creating a 1-dimensional array
arr1d = np.array([1, 2, 3, 4, 5])

# Creating a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Creating arrays with zeros and ones
zeros_arr = np.zeros((3, 4))  # 3x4 array of zeros
ones_arr = np.ones((2, 3))    # 2x3 array of ones

# Creating an array with a range of values
range_arr = np.arange(0, 10, 2)  # Array from 0 to 10 (exclusive) with a step of 2


## Array Operations

In [7]:
array_one = np.array([1, 2, 3, 4, 5])
array_two = np.array([5, 4, 3, 2, 1])

# Element-wise operations
print("Add result: ", array_one + array_two)
print("Subtract result: ", array_one - array_two)
print("Multiply result: ", array_one * array_two)
print("Divide result: ", array_one / array_two)


Add result:  [6 6 6 6 6]
Subtract result:  [-4 -2  0  2  4]
Multiply result:  [5 8 9 8 5]
Divide result:  [0.2 0.5 1.  2.  5. ]


## Universal Functions

In [9]:
arr = np.array([1, 2, 3, 4, 5])

# Square root
sqrt_arr = np.sqrt(arr)

# Exponential function
exp_arr = np.exp(arr)

# Trigonometric functions
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)


## Statistical Operations

In [ ]:
# Basic statistical operations
data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)
median_value = np.median(data)
std_deviation = np.std(data)
variance = np.var(data)

## Linear Algebra Operations

In [14]:
matrix_a = np.array([[3, 4], [7, 2], [5, 9]]) # 3 rows, 2 columns (3 x 2)
matrix_b = np.array([[3, 1, 5], [6, 9, 7]]) # 2 rows, 3 columns (2 x 3)

# result should be 3 x 3
matrix_multiply_result = np.dot(matrix_a, matrix_b)
print(matrix_multiply_result)

[[33 39 43]
 [33 25 49]
 [69 86 88]]
